/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Product_CONSTANTS_H
#define Product_CONSTANTS_H

#include "Product_types.h"

namespace Product { namespace Service {

class ProductConstants {
 public:
  ProductConstants();

  int32_t PDT_SUCCESS_CODE;
  int32_t PDT_FAILED_CODE;
};

extern const ProductConstants g_Product_constants;

}} // namespace

#endif
