/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ProductService_H
#define ProductService_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include "Product_types.h"

namespace Product { namespace Service {

#ifdef _MSC_VER
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class ProductServiceIf {
 public:
  virtual ~ProductServiceIf() {}
  virtual void AddProductType(AddProductTypeRT& _return, const std::string& strSid, const std::string& strUserID, const ProductType& pdttype) = 0;
  virtual void RemoveProductType(ProductRTInfo& _return, const std::string& strSid, const std::string& strUserID, const std::string& strTypeID) = 0;
  virtual void ModifyProductType(ProductRTInfo& _return, const std::string& strSid, const std::string& strUserID, const ProductType& pdttype) = 0;
  virtual void QueryProductType(QueryProductTypeRT& _return, const std::string& strSid, const std::string& strUserID, const std::string& strTypeID) = 0;
  virtual void QueryAllProductType(QueryAllProductTypeRT& _return, const std::string& strSid, const std::string& strUserID) = 0;
  virtual void AddOpenRequest(AddOpenRequestRT& _return, const std::string& strSid, const std::string& strUserID, const OpenRequest& opreq) = 0;
  virtual void RemoveOpenRequest(ProductRTInfo& _return, const std::string& strSid, const std::string& strUserID, const std::string& strOpReqID) = 0;
  virtual void ModifyOpenRequest(ProductRTInfo& _return, const std::string& strSid, const std::string& strUserID, const OpenRequest& opreq) = 0;
  virtual void QueryOpenRequest(QueryOpenRequestRT& _return, const std::string& strSid, const std::string& strUserID, const std::string& strReqID, const std::string& strReqUserID, const std::string& strReqUserName) = 0;
  virtual void QueryAllOpenRequest(QueryAllOpenRequestRT& _return, const std::string& strSid, const std::string& strUserID, const QueryAllOpenRequestParam& qryparam) = 0;
  virtual void AddProduct(AddProductRT& _return, const std::string& strSid, const std::string& strUserID, const ProductInfo& pdt) = 0;
  virtual void RemoveProduct(ProductRTInfo& _return, const std::string& strSid, const std::string& strUserID, const std::string& strPdtID) = 0;
  virtual void ModifyProduct(ProductRTInfo& _return, const std::string& strSid, const std::string& strUserID, const std::string& strPdtID, const ProductInfo& pdt) = 0;
  virtual void QueryProduct(QueryProductRT& _return, const std::string& strSid, const std::string& strUserID, const std::string& strPdtID) = 0;
  virtual void QueryAllProduct(QueryAllProductRT& _return, const std::string& strSid, const std::string& strUserID) = 0;
  virtual void AddProductProperty(AddProductPropertyRT& _return, const std::string& strSid, const std::string& strUserID, const std::string& strPdtID, const ProductProperty& pdtppt) = 0;
  virtual void RemoveProductProperty(ProductRTInfo& _return, const std::string& strSid, const std::string& strUserID, const std::string& strPdtID, const std::string& strPdtpptID) = 0;
};

class ProductServiceIfFactory {
 public:
  typedef ProductServiceIf Handler;

  virtual ~ProductServiceIfFactory() {}

  virtual ProductServiceIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(ProductServiceIf* /* handler */) = 0;
};

class ProductServiceIfSingletonFactory : virtual public ProductServiceIfFactory {
 public:
  ProductServiceIfSingletonFactory(const ::apache::thrift::stdcxx::shared_ptr<ProductServiceIf>& iface) : iface_(iface) {}
  virtual ~ProductServiceIfSingletonFactory() {}

  virtual ProductServiceIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(ProductServiceIf* /* handler */) {}

 protected:
  ::apache::thrift::stdcxx::shared_ptr<ProductServiceIf> iface_;
};

class ProductServiceNull : virtual public ProductServiceIf {
 public:
  virtual ~ProductServiceNull() {}
  void AddProductType(AddProductTypeRT& /* _return */, const std::string& /* strSid */, const std::string& /* strUserID */, const ProductType& /* pdttype */) {
    return;
  }
  void RemoveProductType(ProductRTInfo& /* _return */, const std::string& /* strSid */, const std::string& /* strUserID */, const std::string& /* strTypeID */) {
    return;
  }
  void ModifyProductType(ProductRTInfo& /* _return */, const std::string& /* strSid */, const std::string& /* strUserID */, const ProductType& /* pdttype */) {
    return;
  }
  void QueryProductType(QueryProductTypeRT& /* _return */, const std::string& /* strSid */, const std::string& /* strUserID */, const std::string& /* strTypeID */) {
    return;
  }
  void QueryAllProductType(QueryAllProductTypeRT& /* _return */, const std::string& /* strSid */, const std::string& /* strUserID */) {
    return;
  }
  void AddOpenRequest(AddOpenRequestRT& /* _return */, const std::string& /* strSid */, const std::string& /* strUserID */, const OpenRequest& /* opreq */) {
    return;
  }
  void RemoveOpenRequest(ProductRTInfo& /* _return */, const std::string& /* strSid */, const std::string& /* strUserID */, const std::string& /* strOpReqID */) {
    return;
  }
  void ModifyOpenRequest(ProductRTInfo& /* _return */, const std::string& /* strSid */, const std::string& /* strUserID */, const OpenRequest& /* opreq */) {
    return;
  }
  void QueryOpenRequest(QueryOpenRequestRT& /* _return */, const std::string& /* strSid */, const std::string& /* strUserID */, const std::string& /* strReqID */, const std::string& /* strReqUserID */, const std::string& /* strReqUserName */) {
    return;
  }
  void QueryAllOpenRequest(QueryAllOpenRequestRT& /* _return */, const std::string& /* strSid */, const std::string& /* strUserID */, const QueryAllOpenRequestParam& /* qryparam */) {
    return;
  }
  void AddProduct(AddProductRT& /* _return */, const std::string& /* strSid */, const std::string& /* strUserID */, const ProductInfo& /* pdt */) {
    return;
  }
  void RemoveProduct(ProductRTInfo& /* _return */, const std::string& /* strSid */, const std::string& /* strUserID */, const std::string& /* strPdtID */) {
    return;
  }
  void ModifyProduct(ProductRTInfo& /* _return */, const std::string& /* strSid */, const std::string& /* strUserID */, const std::string& /* strPdtID */, const ProductInfo& /* pdt */) {
    return;
  }
  void QueryProduct(QueryProductRT& /* _return */, const std::string& /* strSid */, const std::string& /* strUserID */, const std::string& /* strPdtID */) {
    return;
  }
  void QueryAllProduct(QueryAllProductRT& /* _return */, const std::string& /* strSid */, const std::string& /* strUserID */) {
    return;
  }
  void AddProductProperty(AddProductPropertyRT& /* _return */, const std::string& /* strSid */, const std::string& /* strUserID */, const std::string& /* strPdtID */, const ProductProperty& /* pdtppt */) {
    return;
  }
  void RemoveProductProperty(ProductRTInfo& /* _return */, const std::string& /* strSid */, const std::string& /* strUserID */, const std::string& /* strPdtID */, const std::string& /* strPdtpptID */) {
    return;
  }
};

typedef struct _ProductService_AddProductType_args__isset {
  _ProductService_AddProductType_args__isset() : strSid(false), strUserID(false), pdttype(false) {}
  bool strSid :1;
  bool strUserID :1;
  bool pdttype :1;
} _ProductService_AddProductType_args__isset;

class ProductService_AddProductType_args {
 public:

  ProductService_AddProductType_args(const ProductService_AddProductType_args&);
  ProductService_AddProductType_args& operator=(const ProductService_AddProductType_args&);
  ProductService_AddProductType_args() : strSid(), strUserID() {
  }

  virtual ~ProductService_AddProductType_args() throw();
  std::string strSid;
  std::string strUserID;
  ProductType pdttype;

  _ProductService_AddProductType_args__isset __isset;

  void __set_strSid(const std::string& val);

  void __set_strUserID(const std::string& val);

  void __set_pdttype(const ProductType& val);

  bool operator == (const ProductService_AddProductType_args & rhs) const
  {
    if (!(strSid == rhs.strSid))
      return false;
    if (!(strUserID == rhs.strUserID))
      return false;
    if (!(pdttype == rhs.pdttype))
      return false;
    return true;
  }
  bool operator != (const ProductService_AddProductType_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ProductService_AddProductType_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class ProductService_AddProductType_pargs {
 public:


  virtual ~ProductService_AddProductType_pargs() throw();
  const std::string* strSid;
  const std::string* strUserID;
  const ProductType* pdttype;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ProductService_AddProductType_result__isset {
  _ProductService_AddProductType_result__isset() : success(false) {}
  bool success :1;
} _ProductService_AddProductType_result__isset;

class ProductService_AddProductType_result {
 public:

  ProductService_AddProductType_result(const ProductService_AddProductType_result&);
  ProductService_AddProductType_result& operator=(const ProductService_AddProductType_result&);
  ProductService_AddProductType_result() {
  }

  virtual ~ProductService_AddProductType_result() throw();
  AddProductTypeRT success;

  _ProductService_AddProductType_result__isset __isset;

  void __set_success(const AddProductTypeRT& val);

  bool operator == (const ProductService_AddProductType_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const ProductService_AddProductType_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ProductService_AddProductType_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ProductService_AddProductType_presult__isset {
  _ProductService_AddProductType_presult__isset() : success(false) {}
  bool success :1;
} _ProductService_AddProductType_presult__isset;

class ProductService_AddProductType_presult {
 public:


  virtual ~ProductService_AddProductType_presult() throw();
  AddProductTypeRT* success;

  _ProductService_AddProductType_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _ProductService_RemoveProductType_args__isset {
  _ProductService_RemoveProductType_args__isset() : strSid(false), strUserID(false), strTypeID(false) {}
  bool strSid :1;
  bool strUserID :1;
  bool strTypeID :1;
} _ProductService_RemoveProductType_args__isset;

class ProductService_RemoveProductType_args {
 public:

  ProductService_RemoveProductType_args(const ProductService_RemoveProductType_args&);
  ProductService_RemoveProductType_args& operator=(const ProductService_RemoveProductType_args&);
  ProductService_RemoveProductType_args() : strSid(), strUserID(), strTypeID() {
  }

  virtual ~ProductService_RemoveProductType_args() throw();
  std::string strSid;
  std::string strUserID;
  std::string strTypeID;

  _ProductService_RemoveProductType_args__isset __isset;

  void __set_strSid(const std::string& val);

  void __set_strUserID(const std::string& val);

  void __set_strTypeID(const std::string& val);

  bool operator == (const ProductService_RemoveProductType_args & rhs) const
  {
    if (!(strSid == rhs.strSid))
      return false;
    if (!(strUserID == rhs.strUserID))
      return false;
    if (!(strTypeID == rhs.strTypeID))
      return false;
    return true;
  }
  bool operator != (const ProductService_RemoveProductType_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ProductService_RemoveProductType_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class ProductService_RemoveProductType_pargs {
 public:


  virtual ~ProductService_RemoveProductType_pargs() throw();
  const std::string* strSid;
  const std::string* strUserID;
  const std::string* strTypeID;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ProductService_RemoveProductType_result__isset {
  _ProductService_RemoveProductType_result__isset() : success(false) {}
  bool success :1;
} _ProductService_RemoveProductType_result__isset;

class ProductService_RemoveProductType_result {
 public:

  ProductService_RemoveProductType_result(const ProductService_RemoveProductType_result&);
  ProductService_RemoveProductType_result& operator=(const ProductService_RemoveProductType_result&);
  ProductService_RemoveProductType_result() {
  }

  virtual ~ProductService_RemoveProductType_result() throw();
  ProductRTInfo success;

  _ProductService_RemoveProductType_result__isset __isset;

  void __set_success(const ProductRTInfo& val);

  bool operator == (const ProductService_RemoveProductType_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const ProductService_RemoveProductType_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ProductService_RemoveProductType_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ProductService_RemoveProductType_presult__isset {
  _ProductService_RemoveProductType_presult__isset() : success(false) {}
  bool success :1;
} _ProductService_RemoveProductType_presult__isset;

class ProductService_RemoveProductType_presult {
 public:


  virtual ~ProductService_RemoveProductType_presult() throw();
  ProductRTInfo* success;

  _ProductService_RemoveProductType_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _ProductService_ModifyProductType_args__isset {
  _ProductService_ModifyProductType_args__isset() : strSid(false), strUserID(false), pdttype(false) {}
  bool strSid :1;
  bool strUserID :1;
  bool pdttype :1;
} _ProductService_ModifyProductType_args__isset;

class ProductService_ModifyProductType_args {
 public:

  ProductService_ModifyProductType_args(const ProductService_ModifyProductType_args&);
  ProductService_ModifyProductType_args& operator=(const ProductService_ModifyProductType_args&);
  ProductService_ModifyProductType_args() : strSid(), strUserID() {
  }

  virtual ~ProductService_ModifyProductType_args() throw();
  std::string strSid;
  std::string strUserID;
  ProductType pdttype;

  _ProductService_ModifyProductType_args__isset __isset;

  void __set_strSid(const std::string& val);

  void __set_strUserID(const std::string& val);

  void __set_pdttype(const ProductType& val);

  bool operator == (const ProductService_ModifyProductType_args & rhs) const
  {
    if (!(strSid == rhs.strSid))
      return false;
    if (!(strUserID == rhs.strUserID))
      return false;
    if (!(pdttype == rhs.pdttype))
      return false;
    return true;
  }
  bool operator != (const ProductService_ModifyProductType_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ProductService_ModifyProductType_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class ProductService_ModifyProductType_pargs {
 public:


  virtual ~ProductService_ModifyProductType_pargs() throw();
  const std::string* strSid;
  const std::string* strUserID;
  const ProductType* pdttype;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ProductService_ModifyProductType_result__isset {
  _ProductService_ModifyProductType_result__isset() : success(false) {}
  bool success :1;
} _ProductService_ModifyProductType_result__isset;

class ProductService_ModifyProductType_result {
 public:

  ProductService_ModifyProductType_result(const ProductService_ModifyProductType_result&);
  ProductService_ModifyProductType_result& operator=(const ProductService_ModifyProductType_result&);
  ProductService_ModifyProductType_result() {
  }

  virtual ~ProductService_ModifyProductType_result() throw();
  ProductRTInfo success;

  _ProductService_ModifyProductType_result__isset __isset;

  void __set_success(const ProductRTInfo& val);

  bool operator == (const ProductService_ModifyProductType_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const ProductService_ModifyProductType_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ProductService_ModifyProductType_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ProductService_ModifyProductType_presult__isset {
  _ProductService_ModifyProductType_presult__isset() : success(false) {}
  bool success :1;
} _ProductService_ModifyProductType_presult__isset;

class ProductService_ModifyProductType_presult {
 public:


  virtual ~ProductService_ModifyProductType_presult() throw();
  ProductRTInfo* success;

  _ProductService_ModifyProductType_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _ProductService_QueryProductType_args__isset {
  _ProductService_QueryProductType_args__isset() : strSid(false), strUserID(false), strTypeID(false) {}
  bool strSid :1;
  bool strUserID :1;
  bool strTypeID :1;
} _ProductService_QueryProductType_args__isset;

class ProductService_QueryProductType_args {
 public:

  ProductService_QueryProductType_args(const ProductService_QueryProductType_args&);
  ProductService_QueryProductType_args& operator=(const ProductService_QueryProductType_args&);
  ProductService_QueryProductType_args() : strSid(), strUserID(), strTypeID() {
  }

  virtual ~ProductService_QueryProductType_args() throw();
  std::string strSid;
  std::string strUserID;
  std::string strTypeID;

  _ProductService_QueryProductType_args__isset __isset;

  void __set_strSid(const std::string& val);

  void __set_strUserID(const std::string& val);

  void __set_strTypeID(const std::string& val);

  bool operator == (const ProductService_QueryProductType_args & rhs) const
  {
    if (!(strSid == rhs.strSid))
      return false;
    if (!(strUserID == rhs.strUserID))
      return false;
    if (!(strTypeID == rhs.strTypeID))
      return false;
    return true;
  }
  bool operator != (const ProductService_QueryProductType_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ProductService_QueryProductType_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class ProductService_QueryProductType_pargs {
 public:


  virtual ~ProductService_QueryProductType_pargs() throw();
  const std::string* strSid;
  const std::string* strUserID;
  const std::string* strTypeID;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ProductService_QueryProductType_result__isset {
  _ProductService_QueryProductType_result__isset() : success(false) {}
  bool success :1;
} _ProductService_QueryProductType_result__isset;

class ProductService_QueryProductType_result {
 public:

  ProductService_QueryProductType_result(const ProductService_QueryProductType_result&);
  ProductService_QueryProductType_result& operator=(const ProductService_QueryProductType_result&);
  ProductService_QueryProductType_result() {
  }

  virtual ~ProductService_QueryProductType_result() throw();
  QueryProductTypeRT success;

  _ProductService_QueryProductType_result__isset __isset;

  void __set_success(const QueryProductTypeRT& val);

  bool operator == (const ProductService_QueryProductType_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const ProductService_QueryProductType_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ProductService_QueryProductType_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ProductService_QueryProductType_presult__isset {
  _ProductService_QueryProductType_presult__isset() : success(false) {}
  bool success :1;
} _ProductService_QueryProductType_presult__isset;

class ProductService_QueryProductType_presult {
 public:


  virtual ~ProductService_QueryProductType_presult() throw();
  QueryProductTypeRT* success;

  _ProductService_QueryProductType_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _ProductService_QueryAllProductType_args__isset {
  _ProductService_QueryAllProductType_args__isset() : strSid(false), strUserID(false) {}
  bool strSid :1;
  bool strUserID :1;
} _ProductService_QueryAllProductType_args__isset;

class ProductService_QueryAllProductType_args {
 public:

  ProductService_QueryAllProductType_args(const ProductService_QueryAllProductType_args&);
  ProductService_QueryAllProductType_args& operator=(const ProductService_QueryAllProductType_args&);
  ProductService_QueryAllProductType_args() : strSid(), strUserID() {
  }

  virtual ~ProductService_QueryAllProductType_args() throw();
  std::string strSid;
  std::string strUserID;

  _ProductService_QueryAllProductType_args__isset __isset;

  void __set_strSid(const std::string& val);

  void __set_strUserID(const std::string& val);

  bool operator == (const ProductService_QueryAllProductType_args & rhs) const
  {
    if (!(strSid == rhs.strSid))
      return false;
    if (!(strUserID == rhs.strUserID))
      return false;
    return true;
  }
  bool operator != (const ProductService_QueryAllProductType_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ProductService_QueryAllProductType_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class ProductService_QueryAllProductType_pargs {
 public:


  virtual ~ProductService_QueryAllProductType_pargs() throw();
  const std::string* strSid;
  const std::string* strUserID;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ProductService_QueryAllProductType_result__isset {
  _ProductService_QueryAllProductType_result__isset() : success(false) {}
  bool success :1;
} _ProductService_QueryAllProductType_result__isset;

class ProductService_QueryAllProductType_result {
 public:

  ProductService_QueryAllProductType_result(const ProductService_QueryAllProductType_result&);
  ProductService_QueryAllProductType_result& operator=(const ProductService_QueryAllProductType_result&);
  ProductService_QueryAllProductType_result() {
  }

  virtual ~ProductService_QueryAllProductType_result() throw();
  QueryAllProductTypeRT success;

  _ProductService_QueryAllProductType_result__isset __isset;

  void __set_success(const QueryAllProductTypeRT& val);

  bool operator == (const ProductService_QueryAllProductType_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const ProductService_QueryAllProductType_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ProductService_QueryAllProductType_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ProductService_QueryAllProductType_presult__isset {
  _ProductService_QueryAllProductType_presult__isset() : success(false) {}
  bool success :1;
} _ProductService_QueryAllProductType_presult__isset;

class ProductService_QueryAllProductType_presult {
 public:


  virtual ~ProductService_QueryAllProductType_presult() throw();
  QueryAllProductTypeRT* success;

  _ProductService_QueryAllProductType_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _ProductService_AddOpenRequest_args__isset {
  _ProductService_AddOpenRequest_args__isset() : strSid(false), strUserID(false), opreq(false) {}
  bool strSid :1;
  bool strUserID :1;
  bool opreq :1;
} _ProductService_AddOpenRequest_args__isset;

class ProductService_AddOpenRequest_args {
 public:

  ProductService_AddOpenRequest_args(const ProductService_AddOpenRequest_args&);
  ProductService_AddOpenRequest_args& operator=(const ProductService_AddOpenRequest_args&);
  ProductService_AddOpenRequest_args() : strSid(), strUserID() {
  }

  virtual ~ProductService_AddOpenRequest_args() throw();
  std::string strSid;
  std::string strUserID;
  OpenRequest opreq;

  _ProductService_AddOpenRequest_args__isset __isset;

  void __set_strSid(const std::string& val);

  void __set_strUserID(const std::string& val);

  void __set_opreq(const OpenRequest& val);

  bool operator == (const ProductService_AddOpenRequest_args & rhs) const
  {
    if (!(strSid == rhs.strSid))
      return false;
    if (!(strUserID == rhs.strUserID))
      return false;
    if (!(opreq == rhs.opreq))
      return false;
    return true;
  }
  bool operator != (const ProductService_AddOpenRequest_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ProductService_AddOpenRequest_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class ProductService_AddOpenRequest_pargs {
 public:


  virtual ~ProductService_AddOpenRequest_pargs() throw();
  const std::string* strSid;
  const std::string* strUserID;
  const OpenRequest* opreq;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ProductService_AddOpenRequest_result__isset {
  _ProductService_AddOpenRequest_result__isset() : success(false) {}
  bool success :1;
} _ProductService_AddOpenRequest_result__isset;

class ProductService_AddOpenRequest_result {
 public:

  ProductService_AddOpenRequest_result(const ProductService_AddOpenRequest_result&);
  ProductService_AddOpenRequest_result& operator=(const ProductService_AddOpenRequest_result&);
  ProductService_AddOpenRequest_result() {
  }

  virtual ~ProductService_AddOpenRequest_result() throw();
  AddOpenRequestRT success;

  _ProductService_AddOpenRequest_result__isset __isset;

  void __set_success(const AddOpenRequestRT& val);

  bool operator == (const ProductService_AddOpenRequest_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const ProductService_AddOpenRequest_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ProductService_AddOpenRequest_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ProductService_AddOpenRequest_presult__isset {
  _ProductService_AddOpenRequest_presult__isset() : success(false) {}
  bool success :1;
} _ProductService_AddOpenRequest_presult__isset;

class ProductService_AddOpenRequest_presult {
 public:


  virtual ~ProductService_AddOpenRequest_presult() throw();
  AddOpenRequestRT* success;

  _ProductService_AddOpenRequest_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _ProductService_RemoveOpenRequest_args__isset {
  _ProductService_RemoveOpenRequest_args__isset() : strSid(false), strUserID(false), strOpReqID(false) {}
  bool strSid :1;
  bool strUserID :1;
  bool strOpReqID :1;
} _ProductService_RemoveOpenRequest_args__isset;

class ProductService_RemoveOpenRequest_args {
 public:

  ProductService_RemoveOpenRequest_args(const ProductService_RemoveOpenRequest_args&);
  ProductService_RemoveOpenRequest_args& operator=(const ProductService_RemoveOpenRequest_args&);
  ProductService_RemoveOpenRequest_args() : strSid(), strUserID(), strOpReqID() {
  }

  virtual ~ProductService_RemoveOpenRequest_args() throw();
  std::string strSid;
  std::string strUserID;
  std::string strOpReqID;

  _ProductService_RemoveOpenRequest_args__isset __isset;

  void __set_strSid(const std::string& val);

  void __set_strUserID(const std::string& val);

  void __set_strOpReqID(const std::string& val);

  bool operator == (const ProductService_RemoveOpenRequest_args & rhs) const
  {
    if (!(strSid == rhs.strSid))
      return false;
    if (!(strUserID == rhs.strUserID))
      return false;
    if (!(strOpReqID == rhs.strOpReqID))
      return false;
    return true;
  }
  bool operator != (const ProductService_RemoveOpenRequest_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ProductService_RemoveOpenRequest_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class ProductService_RemoveOpenRequest_pargs {
 public:


  virtual ~ProductService_RemoveOpenRequest_pargs() throw();
  const std::string* strSid;
  const std::string* strUserID;
  const std::string* strOpReqID;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ProductService_RemoveOpenRequest_result__isset {
  _ProductService_RemoveOpenRequest_result__isset() : success(false) {}
  bool success :1;
} _ProductService_RemoveOpenRequest_result__isset;

class ProductService_RemoveOpenRequest_result {
 public:

  ProductService_RemoveOpenRequest_result(const ProductService_RemoveOpenRequest_result&);
  ProductService_RemoveOpenRequest_result& operator=(const ProductService_RemoveOpenRequest_result&);
  ProductService_RemoveOpenRequest_result() {
  }

  virtual ~ProductService_RemoveOpenRequest_result() throw();
  ProductRTInfo success;

  _ProductService_RemoveOpenRequest_result__isset __isset;

  void __set_success(const ProductRTInfo& val);

  bool operator == (const ProductService_RemoveOpenRequest_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const ProductService_RemoveOpenRequest_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ProductService_RemoveOpenRequest_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ProductService_RemoveOpenRequest_presult__isset {
  _ProductService_RemoveOpenRequest_presult__isset() : success(false) {}
  bool success :1;
} _ProductService_RemoveOpenRequest_presult__isset;

class ProductService_RemoveOpenRequest_presult {
 public:


  virtual ~ProductService_RemoveOpenRequest_presult() throw();
  ProductRTInfo* success;

  _ProductService_RemoveOpenRequest_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _ProductService_ModifyOpenRequest_args__isset {
  _ProductService_ModifyOpenRequest_args__isset() : strSid(false), strUserID(false), opreq(false) {}
  bool strSid :1;
  bool strUserID :1;
  bool opreq :1;
} _ProductService_ModifyOpenRequest_args__isset;

class ProductService_ModifyOpenRequest_args {
 public:

  ProductService_ModifyOpenRequest_args(const ProductService_ModifyOpenRequest_args&);
  ProductService_ModifyOpenRequest_args& operator=(const ProductService_ModifyOpenRequest_args&);
  ProductService_ModifyOpenRequest_args() : strSid(), strUserID() {
  }

  virtual ~ProductService_ModifyOpenRequest_args() throw();
  std::string strSid;
  std::string strUserID;
  OpenRequest opreq;

  _ProductService_ModifyOpenRequest_args__isset __isset;

  void __set_strSid(const std::string& val);

  void __set_strUserID(const std::string& val);

  void __set_opreq(const OpenRequest& val);

  bool operator == (const ProductService_ModifyOpenRequest_args & rhs) const
  {
    if (!(strSid == rhs.strSid))
      return false;
    if (!(strUserID == rhs.strUserID))
      return false;
    if (!(opreq == rhs.opreq))
      return false;
    return true;
  }
  bool operator != (const ProductService_ModifyOpenRequest_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ProductService_ModifyOpenRequest_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class ProductService_ModifyOpenRequest_pargs {
 public:


  virtual ~ProductService_ModifyOpenRequest_pargs() throw();
  const std::string* strSid;
  const std::string* strUserID;
  const OpenRequest* opreq;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ProductService_ModifyOpenRequest_result__isset {
  _ProductService_ModifyOpenRequest_result__isset() : success(false) {}
  bool success :1;
} _ProductService_ModifyOpenRequest_result__isset;

class ProductService_ModifyOpenRequest_result {
 public:

  ProductService_ModifyOpenRequest_result(const ProductService_ModifyOpenRequest_result&);
  ProductService_ModifyOpenRequest_result& operator=(const ProductService_ModifyOpenRequest_result&);
  ProductService_ModifyOpenRequest_result() {
  }

  virtual ~ProductService_ModifyOpenRequest_result() throw();
  ProductRTInfo success;

  _ProductService_ModifyOpenRequest_result__isset __isset;

  void __set_success(const ProductRTInfo& val);

  bool operator == (const ProductService_ModifyOpenRequest_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const ProductService_ModifyOpenRequest_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ProductService_ModifyOpenRequest_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ProductService_ModifyOpenRequest_presult__isset {
  _ProductService_ModifyOpenRequest_presult__isset() : success(false) {}
  bool success :1;
} _ProductService_ModifyOpenRequest_presult__isset;

class ProductService_ModifyOpenRequest_presult {
 public:


  virtual ~ProductService_ModifyOpenRequest_presult() throw();
  ProductRTInfo* success;

  _ProductService_ModifyOpenRequest_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _ProductService_QueryOpenRequest_args__isset {
  _ProductService_QueryOpenRequest_args__isset() : strSid(false), strUserID(false), strReqID(false), strReqUserID(false), strReqUserName(false) {}
  bool strSid :1;
  bool strUserID :1;
  bool strReqID :1;
  bool strReqUserID :1;
  bool strReqUserName :1;
} _ProductService_QueryOpenRequest_args__isset;

class ProductService_QueryOpenRequest_args {
 public:

  ProductService_QueryOpenRequest_args(const ProductService_QueryOpenRequest_args&);
  ProductService_QueryOpenRequest_args& operator=(const ProductService_QueryOpenRequest_args&);
  ProductService_QueryOpenRequest_args() : strSid(), strUserID(), strReqID(), strReqUserID(), strReqUserName() {
  }

  virtual ~ProductService_QueryOpenRequest_args() throw();
  std::string strSid;
  std::string strUserID;
  std::string strReqID;
  std::string strReqUserID;
  std::string strReqUserName;

  _ProductService_QueryOpenRequest_args__isset __isset;

  void __set_strSid(const std::string& val);

  void __set_strUserID(const std::string& val);

  void __set_strReqID(const std::string& val);

  void __set_strReqUserID(const std::string& val);

  void __set_strReqUserName(const std::string& val);

  bool operator == (const ProductService_QueryOpenRequest_args & rhs) const
  {
    if (!(strSid == rhs.strSid))
      return false;
    if (!(strUserID == rhs.strUserID))
      return false;
    if (!(strReqID == rhs.strReqID))
      return false;
    if (!(strReqUserID == rhs.strReqUserID))
      return false;
    if (!(strReqUserName == rhs.strReqUserName))
      return false;
    return true;
  }
  bool operator != (const ProductService_QueryOpenRequest_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ProductService_QueryOpenRequest_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class ProductService_QueryOpenRequest_pargs {
 public:


  virtual ~ProductService_QueryOpenRequest_pargs() throw();
  const std::string* strSid;
  const std::string* strUserID;
  const std::string* strReqID;
  const std::string* strReqUserID;
  const std::string* strReqUserName;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ProductService_QueryOpenRequest_result__isset {
  _ProductService_QueryOpenRequest_result__isset() : success(false) {}
  bool success :1;
} _ProductService_QueryOpenRequest_result__isset;

class ProductService_QueryOpenRequest_result {
 public:

  ProductService_QueryOpenRequest_result(const ProductService_QueryOpenRequest_result&);
  ProductService_QueryOpenRequest_result& operator=(const ProductService_QueryOpenRequest_result&);
  ProductService_QueryOpenRequest_result() {
  }

  virtual ~ProductService_QueryOpenRequest_result() throw();
  QueryOpenRequestRT success;

  _ProductService_QueryOpenRequest_result__isset __isset;

  void __set_success(const QueryOpenRequestRT& val);

  bool operator == (const ProductService_QueryOpenRequest_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const ProductService_QueryOpenRequest_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ProductService_QueryOpenRequest_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ProductService_QueryOpenRequest_presult__isset {
  _ProductService_QueryOpenRequest_presult__isset() : success(false) {}
  bool success :1;
} _ProductService_QueryOpenRequest_presult__isset;

class ProductService_QueryOpenRequest_presult {
 public:


  virtual ~ProductService_QueryOpenRequest_presult() throw();
  QueryOpenRequestRT* success;

  _ProductService_QueryOpenRequest_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _ProductService_QueryAllOpenRequest_args__isset {
  _ProductService_QueryAllOpenRequest_args__isset() : strSid(false), strUserID(false), qryparam(false) {}
  bool strSid :1;
  bool strUserID :1;
  bool qryparam :1;
} _ProductService_QueryAllOpenRequest_args__isset;

class ProductService_QueryAllOpenRequest_args {
 public:

  ProductService_QueryAllOpenRequest_args(const ProductService_QueryAllOpenRequest_args&);
  ProductService_QueryAllOpenRequest_args& operator=(const ProductService_QueryAllOpenRequest_args&);
  ProductService_QueryAllOpenRequest_args() : strSid(), strUserID() {
  }

  virtual ~ProductService_QueryAllOpenRequest_args() throw();
  std::string strSid;
  std::string strUserID;
  QueryAllOpenRequestParam qryparam;

  _ProductService_QueryAllOpenRequest_args__isset __isset;

  void __set_strSid(const std::string& val);

  void __set_strUserID(const std::string& val);

  void __set_qryparam(const QueryAllOpenRequestParam& val);

  bool operator == (const ProductService_QueryAllOpenRequest_args & rhs) const
  {
    if (!(strSid == rhs.strSid))
      return false;
    if (!(strUserID == rhs.strUserID))
      return false;
    if (!(qryparam == rhs.qryparam))
      return false;
    return true;
  }
  bool operator != (const ProductService_QueryAllOpenRequest_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ProductService_QueryAllOpenRequest_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class ProductService_QueryAllOpenRequest_pargs {
 public:


  virtual ~ProductService_QueryAllOpenRequest_pargs() throw();
  const std::string* strSid;
  const std::string* strUserID;
  const QueryAllOpenRequestParam* qryparam;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ProductService_QueryAllOpenRequest_result__isset {
  _ProductService_QueryAllOpenRequest_result__isset() : success(false) {}
  bool success :1;
} _ProductService_QueryAllOpenRequest_result__isset;

class ProductService_QueryAllOpenRequest_result {
 public:

  ProductService_QueryAllOpenRequest_result(const ProductService_QueryAllOpenRequest_result&);
  ProductService_QueryAllOpenRequest_result& operator=(const ProductService_QueryAllOpenRequest_result&);
  ProductService_QueryAllOpenRequest_result() {
  }

  virtual ~ProductService_QueryAllOpenRequest_result() throw();
  QueryAllOpenRequestRT success;

  _ProductService_QueryAllOpenRequest_result__isset __isset;

  void __set_success(const QueryAllOpenRequestRT& val);

  bool operator == (const ProductService_QueryAllOpenRequest_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const ProductService_QueryAllOpenRequest_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ProductService_QueryAllOpenRequest_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ProductService_QueryAllOpenRequest_presult__isset {
  _ProductService_QueryAllOpenRequest_presult__isset() : success(false) {}
  bool success :1;
} _ProductService_QueryAllOpenRequest_presult__isset;

class ProductService_QueryAllOpenRequest_presult {
 public:


  virtual ~ProductService_QueryAllOpenRequest_presult() throw();
  QueryAllOpenRequestRT* success;

  _ProductService_QueryAllOpenRequest_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _ProductService_AddProduct_args__isset {
  _ProductService_AddProduct_args__isset() : strSid(false), strUserID(false), pdt(false) {}
  bool strSid :1;
  bool strUserID :1;
  bool pdt :1;
} _ProductService_AddProduct_args__isset;

class ProductService_AddProduct_args {
 public:

  ProductService_AddProduct_args(const ProductService_AddProduct_args&);
  ProductService_AddProduct_args& operator=(const ProductService_AddProduct_args&);
  ProductService_AddProduct_args() : strSid(), strUserID() {
  }

  virtual ~ProductService_AddProduct_args() throw();
  std::string strSid;
  std::string strUserID;
  ProductInfo pdt;

  _ProductService_AddProduct_args__isset __isset;

  void __set_strSid(const std::string& val);

  void __set_strUserID(const std::string& val);

  void __set_pdt(const ProductInfo& val);

  bool operator == (const ProductService_AddProduct_args & rhs) const
  {
    if (!(strSid == rhs.strSid))
      return false;
    if (!(strUserID == rhs.strUserID))
      return false;
    if (!(pdt == rhs.pdt))
      return false;
    return true;
  }
  bool operator != (const ProductService_AddProduct_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ProductService_AddProduct_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class ProductService_AddProduct_pargs {
 public:


  virtual ~ProductService_AddProduct_pargs() throw();
  const std::string* strSid;
  const std::string* strUserID;
  const ProductInfo* pdt;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ProductService_AddProduct_result__isset {
  _ProductService_AddProduct_result__isset() : success(false) {}
  bool success :1;
} _ProductService_AddProduct_result__isset;

class ProductService_AddProduct_result {
 public:

  ProductService_AddProduct_result(const ProductService_AddProduct_result&);
  ProductService_AddProduct_result& operator=(const ProductService_AddProduct_result&);
  ProductService_AddProduct_result() {
  }

  virtual ~ProductService_AddProduct_result() throw();
  AddProductRT success;

  _ProductService_AddProduct_result__isset __isset;

  void __set_success(const AddProductRT& val);

  bool operator == (const ProductService_AddProduct_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const ProductService_AddProduct_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ProductService_AddProduct_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ProductService_AddProduct_presult__isset {
  _ProductService_AddProduct_presult__isset() : success(false) {}
  bool success :1;
} _ProductService_AddProduct_presult__isset;

class ProductService_AddProduct_presult {
 public:


  virtual ~ProductService_AddProduct_presult() throw();
  AddProductRT* success;

  _ProductService_AddProduct_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _ProductService_RemoveProduct_args__isset {
  _ProductService_RemoveProduct_args__isset() : strSid(false), strUserID(false), strPdtID(false) {}
  bool strSid :1;
  bool strUserID :1;
  bool strPdtID :1;
} _ProductService_RemoveProduct_args__isset;

class ProductService_RemoveProduct_args {
 public:

  ProductService_RemoveProduct_args(const ProductService_RemoveProduct_args&);
  ProductService_RemoveProduct_args& operator=(const ProductService_RemoveProduct_args&);
  ProductService_RemoveProduct_args() : strSid(), strUserID(), strPdtID() {
  }

  virtual ~ProductService_RemoveProduct_args() throw();
  std::string strSid;
  std::string strUserID;
  std::string strPdtID;

  _ProductService_RemoveProduct_args__isset __isset;

  void __set_strSid(const std::string& val);

  void __set_strUserID(const std::string& val);

  void __set_strPdtID(const std::string& val);

  bool operator == (const ProductService_RemoveProduct_args & rhs) const
  {
    if (!(strSid == rhs.strSid))
      return false;
    if (!(strUserID == rhs.strUserID))
      return false;
    if (!(strPdtID == rhs.strPdtID))
      return false;
    return true;
  }
  bool operator != (const ProductService_RemoveProduct_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ProductService_RemoveProduct_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class ProductService_RemoveProduct_pargs {
 public:


  virtual ~ProductService_RemoveProduct_pargs() throw();
  const std::string* strSid;
  const std::string* strUserID;
  const std::string* strPdtID;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ProductService_RemoveProduct_result__isset {
  _ProductService_RemoveProduct_result__isset() : success(false) {}
  bool success :1;
} _ProductService_RemoveProduct_result__isset;

class ProductService_RemoveProduct_result {
 public:

  ProductService_RemoveProduct_result(const ProductService_RemoveProduct_result&);
  ProductService_RemoveProduct_result& operator=(const ProductService_RemoveProduct_result&);
  ProductService_RemoveProduct_result() {
  }

  virtual ~ProductService_RemoveProduct_result() throw();
  ProductRTInfo success;

  _ProductService_RemoveProduct_result__isset __isset;

  void __set_success(const ProductRTInfo& val);

  bool operator == (const ProductService_RemoveProduct_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const ProductService_RemoveProduct_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ProductService_RemoveProduct_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ProductService_RemoveProduct_presult__isset {
  _ProductService_RemoveProduct_presult__isset() : success(false) {}
  bool success :1;
} _ProductService_RemoveProduct_presult__isset;

class ProductService_RemoveProduct_presult {
 public:


  virtual ~ProductService_RemoveProduct_presult() throw();
  ProductRTInfo* success;

  _ProductService_RemoveProduct_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _ProductService_ModifyProduct_args__isset {
  _ProductService_ModifyProduct_args__isset() : strSid(false), strUserID(false), strPdtID(false), pdt(false) {}
  bool strSid :1;
  bool strUserID :1;
  bool strPdtID :1;
  bool pdt :1;
} _ProductService_ModifyProduct_args__isset;

class ProductService_ModifyProduct_args {
 public:

  ProductService_ModifyProduct_args(const ProductService_ModifyProduct_args&);
  ProductService_ModifyProduct_args& operator=(const ProductService_ModifyProduct_args&);
  ProductService_ModifyProduct_args() : strSid(), strUserID(), strPdtID() {
  }

  virtual ~ProductService_ModifyProduct_args() throw();
  std::string strSid;
  std::string strUserID;
  std::string strPdtID;
  ProductInfo pdt;

  _ProductService_ModifyProduct_args__isset __isset;

  void __set_strSid(const std::string& val);

  void __set_strUserID(const std::string& val);

  void __set_strPdtID(const std::string& val);

  void __set_pdt(const ProductInfo& val);

  bool operator == (const ProductService_ModifyProduct_args & rhs) const
  {
    if (!(strSid == rhs.strSid))
      return false;
    if (!(strUserID == rhs.strUserID))
      return false;
    if (!(strPdtID == rhs.strPdtID))
      return false;
    if (!(pdt == rhs.pdt))
      return false;
    return true;
  }
  bool operator != (const ProductService_ModifyProduct_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ProductService_ModifyProduct_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class ProductService_ModifyProduct_pargs {
 public:


  virtual ~ProductService_ModifyProduct_pargs() throw();
  const std::string* strSid;
  const std::string* strUserID;
  const std::string* strPdtID;
  const ProductInfo* pdt;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ProductService_ModifyProduct_result__isset {
  _ProductService_ModifyProduct_result__isset() : success(false) {}
  bool success :1;
} _ProductService_ModifyProduct_result__isset;

class ProductService_ModifyProduct_result {
 public:

  ProductService_ModifyProduct_result(const ProductService_ModifyProduct_result&);
  ProductService_ModifyProduct_result& operator=(const ProductService_ModifyProduct_result&);
  ProductService_ModifyProduct_result() {
  }

  virtual ~ProductService_ModifyProduct_result() throw();
  ProductRTInfo success;

  _ProductService_ModifyProduct_result__isset __isset;

  void __set_success(const ProductRTInfo& val);

  bool operator == (const ProductService_ModifyProduct_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const ProductService_ModifyProduct_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ProductService_ModifyProduct_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ProductService_ModifyProduct_presult__isset {
  _ProductService_ModifyProduct_presult__isset() : success(false) {}
  bool success :1;
} _ProductService_ModifyProduct_presult__isset;

class ProductService_ModifyProduct_presult {
 public:


  virtual ~ProductService_ModifyProduct_presult() throw();
  ProductRTInfo* success;

  _ProductService_ModifyProduct_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _ProductService_QueryProduct_args__isset {
  _ProductService_QueryProduct_args__isset() : strSid(false), strUserID(false), strPdtID(false) {}
  bool strSid :1;
  bool strUserID :1;
  bool strPdtID :1;
} _ProductService_QueryProduct_args__isset;

class ProductService_QueryProduct_args {
 public:

  ProductService_QueryProduct_args(const ProductService_QueryProduct_args&);
  ProductService_QueryProduct_args& operator=(const ProductService_QueryProduct_args&);
  ProductService_QueryProduct_args() : strSid(), strUserID(), strPdtID() {
  }

  virtual ~ProductService_QueryProduct_args() throw();
  std::string strSid;
  std::string strUserID;
  std::string strPdtID;

  _ProductService_QueryProduct_args__isset __isset;

  void __set_strSid(const std::string& val);

  void __set_strUserID(const std::string& val);

  void __set_strPdtID(const std::string& val);

  bool operator == (const ProductService_QueryProduct_args & rhs) const
  {
    if (!(strSid == rhs.strSid))
      return false;
    if (!(strUserID == rhs.strUserID))
      return false;
    if (!(strPdtID == rhs.strPdtID))
      return false;
    return true;
  }
  bool operator != (const ProductService_QueryProduct_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ProductService_QueryProduct_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class ProductService_QueryProduct_pargs {
 public:


  virtual ~ProductService_QueryProduct_pargs() throw();
  const std::string* strSid;
  const std::string* strUserID;
  const std::string* strPdtID;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ProductService_QueryProduct_result__isset {
  _ProductService_QueryProduct_result__isset() : success(false) {}
  bool success :1;
} _ProductService_QueryProduct_result__isset;

class ProductService_QueryProduct_result {
 public:

  ProductService_QueryProduct_result(const ProductService_QueryProduct_result&);
  ProductService_QueryProduct_result& operator=(const ProductService_QueryProduct_result&);
  ProductService_QueryProduct_result() {
  }

  virtual ~ProductService_QueryProduct_result() throw();
  QueryProductRT success;

  _ProductService_QueryProduct_result__isset __isset;

  void __set_success(const QueryProductRT& val);

  bool operator == (const ProductService_QueryProduct_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const ProductService_QueryProduct_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ProductService_QueryProduct_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ProductService_QueryProduct_presult__isset {
  _ProductService_QueryProduct_presult__isset() : success(false) {}
  bool success :1;
} _ProductService_QueryProduct_presult__isset;

class ProductService_QueryProduct_presult {
 public:


  virtual ~ProductService_QueryProduct_presult() throw();
  QueryProductRT* success;

  _ProductService_QueryProduct_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _ProductService_QueryAllProduct_args__isset {
  _ProductService_QueryAllProduct_args__isset() : strSid(false), strUserID(false) {}
  bool strSid :1;
  bool strUserID :1;
} _ProductService_QueryAllProduct_args__isset;

class ProductService_QueryAllProduct_args {
 public:

  ProductService_QueryAllProduct_args(const ProductService_QueryAllProduct_args&);
  ProductService_QueryAllProduct_args& operator=(const ProductService_QueryAllProduct_args&);
  ProductService_QueryAllProduct_args() : strSid(), strUserID() {
  }

  virtual ~ProductService_QueryAllProduct_args() throw();
  std::string strSid;
  std::string strUserID;

  _ProductService_QueryAllProduct_args__isset __isset;

  void __set_strSid(const std::string& val);

  void __set_strUserID(const std::string& val);

  bool operator == (const ProductService_QueryAllProduct_args & rhs) const
  {
    if (!(strSid == rhs.strSid))
      return false;
    if (!(strUserID == rhs.strUserID))
      return false;
    return true;
  }
  bool operator != (const ProductService_QueryAllProduct_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ProductService_QueryAllProduct_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class ProductService_QueryAllProduct_pargs {
 public:


  virtual ~ProductService_QueryAllProduct_pargs() throw();
  const std::string* strSid;
  const std::string* strUserID;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ProductService_QueryAllProduct_result__isset {
  _ProductService_QueryAllProduct_result__isset() : success(false) {}
  bool success :1;
} _ProductService_QueryAllProduct_result__isset;

class ProductService_QueryAllProduct_result {
 public:

  ProductService_QueryAllProduct_result(const ProductService_QueryAllProduct_result&);
  ProductService_QueryAllProduct_result& operator=(const ProductService_QueryAllProduct_result&);
  ProductService_QueryAllProduct_result() {
  }

  virtual ~ProductService_QueryAllProduct_result() throw();
  QueryAllProductRT success;

  _ProductService_QueryAllProduct_result__isset __isset;

  void __set_success(const QueryAllProductRT& val);

  bool operator == (const ProductService_QueryAllProduct_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const ProductService_QueryAllProduct_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ProductService_QueryAllProduct_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ProductService_QueryAllProduct_presult__isset {
  _ProductService_QueryAllProduct_presult__isset() : success(false) {}
  bool success :1;
} _ProductService_QueryAllProduct_presult__isset;

class ProductService_QueryAllProduct_presult {
 public:


  virtual ~ProductService_QueryAllProduct_presult() throw();
  QueryAllProductRT* success;

  _ProductService_QueryAllProduct_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _ProductService_AddProductProperty_args__isset {
  _ProductService_AddProductProperty_args__isset() : strSid(false), strUserID(false), strPdtID(false), pdtppt(false) {}
  bool strSid :1;
  bool strUserID :1;
  bool strPdtID :1;
  bool pdtppt :1;
} _ProductService_AddProductProperty_args__isset;

class ProductService_AddProductProperty_args {
 public:

  ProductService_AddProductProperty_args(const ProductService_AddProductProperty_args&);
  ProductService_AddProductProperty_args& operator=(const ProductService_AddProductProperty_args&);
  ProductService_AddProductProperty_args() : strSid(), strUserID(), strPdtID() {
  }

  virtual ~ProductService_AddProductProperty_args() throw();
  std::string strSid;
  std::string strUserID;
  std::string strPdtID;
  ProductProperty pdtppt;

  _ProductService_AddProductProperty_args__isset __isset;

  void __set_strSid(const std::string& val);

  void __set_strUserID(const std::string& val);

  void __set_strPdtID(const std::string& val);

  void __set_pdtppt(const ProductProperty& val);

  bool operator == (const ProductService_AddProductProperty_args & rhs) const
  {
    if (!(strSid == rhs.strSid))
      return false;
    if (!(strUserID == rhs.strUserID))
      return false;
    if (!(strPdtID == rhs.strPdtID))
      return false;
    if (!(pdtppt == rhs.pdtppt))
      return false;
    return true;
  }
  bool operator != (const ProductService_AddProductProperty_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ProductService_AddProductProperty_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class ProductService_AddProductProperty_pargs {
 public:


  virtual ~ProductService_AddProductProperty_pargs() throw();
  const std::string* strSid;
  const std::string* strUserID;
  const std::string* strPdtID;
  const ProductProperty* pdtppt;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ProductService_AddProductProperty_result__isset {
  _ProductService_AddProductProperty_result__isset() : success(false) {}
  bool success :1;
} _ProductService_AddProductProperty_result__isset;

class ProductService_AddProductProperty_result {
 public:

  ProductService_AddProductProperty_result(const ProductService_AddProductProperty_result&);
  ProductService_AddProductProperty_result& operator=(const ProductService_AddProductProperty_result&);
  ProductService_AddProductProperty_result() {
  }

  virtual ~ProductService_AddProductProperty_result() throw();
  AddProductPropertyRT success;

  _ProductService_AddProductProperty_result__isset __isset;

  void __set_success(const AddProductPropertyRT& val);

  bool operator == (const ProductService_AddProductProperty_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const ProductService_AddProductProperty_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ProductService_AddProductProperty_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ProductService_AddProductProperty_presult__isset {
  _ProductService_AddProductProperty_presult__isset() : success(false) {}
  bool success :1;
} _ProductService_AddProductProperty_presult__isset;

class ProductService_AddProductProperty_presult {
 public:


  virtual ~ProductService_AddProductProperty_presult() throw();
  AddProductPropertyRT* success;

  _ProductService_AddProductProperty_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _ProductService_RemoveProductProperty_args__isset {
  _ProductService_RemoveProductProperty_args__isset() : strSid(false), strUserID(false), strPdtID(false), strPdtpptID(false) {}
  bool strSid :1;
  bool strUserID :1;
  bool strPdtID :1;
  bool strPdtpptID :1;
} _ProductService_RemoveProductProperty_args__isset;

class ProductService_RemoveProductProperty_args {
 public:

  ProductService_RemoveProductProperty_args(const ProductService_RemoveProductProperty_args&);
  ProductService_RemoveProductProperty_args& operator=(const ProductService_RemoveProductProperty_args&);
  ProductService_RemoveProductProperty_args() : strSid(), strUserID(), strPdtID(), strPdtpptID() {
  }

  virtual ~ProductService_RemoveProductProperty_args() throw();
  std::string strSid;
  std::string strUserID;
  std::string strPdtID;
  std::string strPdtpptID;

  _ProductService_RemoveProductProperty_args__isset __isset;

  void __set_strSid(const std::string& val);

  void __set_strUserID(const std::string& val);

  void __set_strPdtID(const std::string& val);

  void __set_strPdtpptID(const std::string& val);

  bool operator == (const ProductService_RemoveProductProperty_args & rhs) const
  {
    if (!(strSid == rhs.strSid))
      return false;
    if (!(strUserID == rhs.strUserID))
      return false;
    if (!(strPdtID == rhs.strPdtID))
      return false;
    if (!(strPdtpptID == rhs.strPdtpptID))
      return false;
    return true;
  }
  bool operator != (const ProductService_RemoveProductProperty_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ProductService_RemoveProductProperty_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class ProductService_RemoveProductProperty_pargs {
 public:


  virtual ~ProductService_RemoveProductProperty_pargs() throw();
  const std::string* strSid;
  const std::string* strUserID;
  const std::string* strPdtID;
  const std::string* strPdtpptID;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ProductService_RemoveProductProperty_result__isset {
  _ProductService_RemoveProductProperty_result__isset() : success(false) {}
  bool success :1;
} _ProductService_RemoveProductProperty_result__isset;

class ProductService_RemoveProductProperty_result {
 public:

  ProductService_RemoveProductProperty_result(const ProductService_RemoveProductProperty_result&);
  ProductService_RemoveProductProperty_result& operator=(const ProductService_RemoveProductProperty_result&);
  ProductService_RemoveProductProperty_result() {
  }

  virtual ~ProductService_RemoveProductProperty_result() throw();
  ProductRTInfo success;

  _ProductService_RemoveProductProperty_result__isset __isset;

  void __set_success(const ProductRTInfo& val);

  bool operator == (const ProductService_RemoveProductProperty_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const ProductService_RemoveProductProperty_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ProductService_RemoveProductProperty_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ProductService_RemoveProductProperty_presult__isset {
  _ProductService_RemoveProductProperty_presult__isset() : success(false) {}
  bool success :1;
} _ProductService_RemoveProductProperty_presult__isset;

class ProductService_RemoveProductProperty_presult {
 public:


  virtual ~ProductService_RemoveProductProperty_presult() throw();
  ProductRTInfo* success;

  _ProductService_RemoveProductProperty_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class ProductServiceClient : virtual public ProductServiceIf {
 public:
  ProductServiceClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  ProductServiceClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void AddProductType(AddProductTypeRT& _return, const std::string& strSid, const std::string& strUserID, const ProductType& pdttype);
  void send_AddProductType(const std::string& strSid, const std::string& strUserID, const ProductType& pdttype);
  void recv_AddProductType(AddProductTypeRT& _return);
  void RemoveProductType(ProductRTInfo& _return, const std::string& strSid, const std::string& strUserID, const std::string& strTypeID);
  void send_RemoveProductType(const std::string& strSid, const std::string& strUserID, const std::string& strTypeID);
  void recv_RemoveProductType(ProductRTInfo& _return);
  void ModifyProductType(ProductRTInfo& _return, const std::string& strSid, const std::string& strUserID, const ProductType& pdttype);
  void send_ModifyProductType(const std::string& strSid, const std::string& strUserID, const ProductType& pdttype);
  void recv_ModifyProductType(ProductRTInfo& _return);
  void QueryProductType(QueryProductTypeRT& _return, const std::string& strSid, const std::string& strUserID, const std::string& strTypeID);
  void send_QueryProductType(const std::string& strSid, const std::string& strUserID, const std::string& strTypeID);
  void recv_QueryProductType(QueryProductTypeRT& _return);
  void QueryAllProductType(QueryAllProductTypeRT& _return, const std::string& strSid, const std::string& strUserID);
  void send_QueryAllProductType(const std::string& strSid, const std::string& strUserID);
  void recv_QueryAllProductType(QueryAllProductTypeRT& _return);
  void AddOpenRequest(AddOpenRequestRT& _return, const std::string& strSid, const std::string& strUserID, const OpenRequest& opreq);
  void send_AddOpenRequest(const std::string& strSid, const std::string& strUserID, const OpenRequest& opreq);
  void recv_AddOpenRequest(AddOpenRequestRT& _return);
  void RemoveOpenRequest(ProductRTInfo& _return, const std::string& strSid, const std::string& strUserID, const std::string& strOpReqID);
  void send_RemoveOpenRequest(const std::string& strSid, const std::string& strUserID, const std::string& strOpReqID);
  void recv_RemoveOpenRequest(ProductRTInfo& _return);
  void ModifyOpenRequest(ProductRTInfo& _return, const std::string& strSid, const std::string& strUserID, const OpenRequest& opreq);
  void send_ModifyOpenRequest(const std::string& strSid, const std::string& strUserID, const OpenRequest& opreq);
  void recv_ModifyOpenRequest(ProductRTInfo& _return);
  void QueryOpenRequest(QueryOpenRequestRT& _return, const std::string& strSid, const std::string& strUserID, const std::string& strReqID, const std::string& strReqUserID, const std::string& strReqUserName);
  void send_QueryOpenRequest(const std::string& strSid, const std::string& strUserID, const std::string& strReqID, const std::string& strReqUserID, const std::string& strReqUserName);
  void recv_QueryOpenRequest(QueryOpenRequestRT& _return);
  void QueryAllOpenRequest(QueryAllOpenRequestRT& _return, const std::string& strSid, const std::string& strUserID, const QueryAllOpenRequestParam& qryparam);
  void send_QueryAllOpenRequest(const std::string& strSid, const std::string& strUserID, const QueryAllOpenRequestParam& qryparam);
  void recv_QueryAllOpenRequest(QueryAllOpenRequestRT& _return);
  void AddProduct(AddProductRT& _return, const std::string& strSid, const std::string& strUserID, const ProductInfo& pdt);
  void send_AddProduct(const std::string& strSid, const std::string& strUserID, const ProductInfo& pdt);
  void recv_AddProduct(AddProductRT& _return);
  void RemoveProduct(ProductRTInfo& _return, const std::string& strSid, const std::string& strUserID, const std::string& strPdtID);
  void send_RemoveProduct(const std::string& strSid, const std::string& strUserID, const std::string& strPdtID);
  void recv_RemoveProduct(ProductRTInfo& _return);
  void ModifyProduct(ProductRTInfo& _return, const std::string& strSid, const std::string& strUserID, const std::string& strPdtID, const ProductInfo& pdt);
  void send_ModifyProduct(const std::string& strSid, const std::string& strUserID, const std::string& strPdtID, const ProductInfo& pdt);
  void recv_ModifyProduct(ProductRTInfo& _return);
  void QueryProduct(QueryProductRT& _return, const std::string& strSid, const std::string& strUserID, const std::string& strPdtID);
  void send_QueryProduct(const std::string& strSid, const std::string& strUserID, const std::string& strPdtID);
  void recv_QueryProduct(QueryProductRT& _return);
  void QueryAllProduct(QueryAllProductRT& _return, const std::string& strSid, const std::string& strUserID);
  void send_QueryAllProduct(const std::string& strSid, const std::string& strUserID);
  void recv_QueryAllProduct(QueryAllProductRT& _return);
  void AddProductProperty(AddProductPropertyRT& _return, const std::string& strSid, const std::string& strUserID, const std::string& strPdtID, const ProductProperty& pdtppt);
  void send_AddProductProperty(const std::string& strSid, const std::string& strUserID, const std::string& strPdtID, const ProductProperty& pdtppt);
  void recv_AddProductProperty(AddProductPropertyRT& _return);
  void RemoveProductProperty(ProductRTInfo& _return, const std::string& strSid, const std::string& strUserID, const std::string& strPdtID, const std::string& strPdtpptID);
  void send_RemoveProductProperty(const std::string& strSid, const std::string& strUserID, const std::string& strPdtID, const std::string& strPdtpptID);
  void recv_RemoveProductProperty(ProductRTInfo& _return);
 protected:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class ProductServiceProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  ::apache::thrift::stdcxx::shared_ptr<ProductServiceIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (ProductServiceProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_AddProductType(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_RemoveProductType(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_ModifyProductType(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_QueryProductType(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_QueryAllProductType(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_AddOpenRequest(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_RemoveOpenRequest(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_ModifyOpenRequest(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_QueryOpenRequest(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_QueryAllOpenRequest(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_AddProduct(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_RemoveProduct(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_ModifyProduct(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_QueryProduct(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_QueryAllProduct(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_AddProductProperty(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_RemoveProductProperty(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  ProductServiceProcessor(::apache::thrift::stdcxx::shared_ptr<ProductServiceIf> iface) :
    iface_(iface) {
    processMap_["AddProductType"] = &ProductServiceProcessor::process_AddProductType;
    processMap_["RemoveProductType"] = &ProductServiceProcessor::process_RemoveProductType;
    processMap_["ModifyProductType"] = &ProductServiceProcessor::process_ModifyProductType;
    processMap_["QueryProductType"] = &ProductServiceProcessor::process_QueryProductType;
    processMap_["QueryAllProductType"] = &ProductServiceProcessor::process_QueryAllProductType;
    processMap_["AddOpenRequest"] = &ProductServiceProcessor::process_AddOpenRequest;
    processMap_["RemoveOpenRequest"] = &ProductServiceProcessor::process_RemoveOpenRequest;
    processMap_["ModifyOpenRequest"] = &ProductServiceProcessor::process_ModifyOpenRequest;
    processMap_["QueryOpenRequest"] = &ProductServiceProcessor::process_QueryOpenRequest;
    processMap_["QueryAllOpenRequest"] = &ProductServiceProcessor::process_QueryAllOpenRequest;
    processMap_["AddProduct"] = &ProductServiceProcessor::process_AddProduct;
    processMap_["RemoveProduct"] = &ProductServiceProcessor::process_RemoveProduct;
    processMap_["ModifyProduct"] = &ProductServiceProcessor::process_ModifyProduct;
    processMap_["QueryProduct"] = &ProductServiceProcessor::process_QueryProduct;
    processMap_["QueryAllProduct"] = &ProductServiceProcessor::process_QueryAllProduct;
    processMap_["AddProductProperty"] = &ProductServiceProcessor::process_AddProductProperty;
    processMap_["RemoveProductProperty"] = &ProductServiceProcessor::process_RemoveProductProperty;
  }

  virtual ~ProductServiceProcessor() {}
};

class ProductServiceProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  ProductServiceProcessorFactory(const ::apache::thrift::stdcxx::shared_ptr< ProductServiceIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::apache::thrift::stdcxx::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::apache::thrift::stdcxx::shared_ptr< ProductServiceIfFactory > handlerFactory_;
};

class ProductServiceMultiface : virtual public ProductServiceIf {
 public:
  ProductServiceMultiface(std::vector<apache::thrift::stdcxx::shared_ptr<ProductServiceIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~ProductServiceMultiface() {}
 protected:
  std::vector<apache::thrift::stdcxx::shared_ptr<ProductServiceIf> > ifaces_;
  ProductServiceMultiface() {}
  void add(::apache::thrift::stdcxx::shared_ptr<ProductServiceIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void AddProductType(AddProductTypeRT& _return, const std::string& strSid, const std::string& strUserID, const ProductType& pdttype) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->AddProductType(_return, strSid, strUserID, pdttype);
    }
    ifaces_[i]->AddProductType(_return, strSid, strUserID, pdttype);
    return;
  }

  void RemoveProductType(ProductRTInfo& _return, const std::string& strSid, const std::string& strUserID, const std::string& strTypeID) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->RemoveProductType(_return, strSid, strUserID, strTypeID);
    }
    ifaces_[i]->RemoveProductType(_return, strSid, strUserID, strTypeID);
    return;
  }

  void ModifyProductType(ProductRTInfo& _return, const std::string& strSid, const std::string& strUserID, const ProductType& pdttype) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->ModifyProductType(_return, strSid, strUserID, pdttype);
    }
    ifaces_[i]->ModifyProductType(_return, strSid, strUserID, pdttype);
    return;
  }

  void QueryProductType(QueryProductTypeRT& _return, const std::string& strSid, const std::string& strUserID, const std::string& strTypeID) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->QueryProductType(_return, strSid, strUserID, strTypeID);
    }
    ifaces_[i]->QueryProductType(_return, strSid, strUserID, strTypeID);
    return;
  }

  void QueryAllProductType(QueryAllProductTypeRT& _return, const std::string& strSid, const std::string& strUserID) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->QueryAllProductType(_return, strSid, strUserID);
    }
    ifaces_[i]->QueryAllProductType(_return, strSid, strUserID);
    return;
  }

  void AddOpenRequest(AddOpenRequestRT& _return, const std::string& strSid, const std::string& strUserID, const OpenRequest& opreq) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->AddOpenRequest(_return, strSid, strUserID, opreq);
    }
    ifaces_[i]->AddOpenRequest(_return, strSid, strUserID, opreq);
    return;
  }

  void RemoveOpenRequest(ProductRTInfo& _return, const std::string& strSid, const std::string& strUserID, const std::string& strOpReqID) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->RemoveOpenRequest(_return, strSid, strUserID, strOpReqID);
    }
    ifaces_[i]->RemoveOpenRequest(_return, strSid, strUserID, strOpReqID);
    return;
  }

  void ModifyOpenRequest(ProductRTInfo& _return, const std::string& strSid, const std::string& strUserID, const OpenRequest& opreq) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->ModifyOpenRequest(_return, strSid, strUserID, opreq);
    }
    ifaces_[i]->ModifyOpenRequest(_return, strSid, strUserID, opreq);
    return;
  }

  void QueryOpenRequest(QueryOpenRequestRT& _return, const std::string& strSid, const std::string& strUserID, const std::string& strReqID, const std::string& strReqUserID, const std::string& strReqUserName) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->QueryOpenRequest(_return, strSid, strUserID, strReqID, strReqUserID, strReqUserName);
    }
    ifaces_[i]->QueryOpenRequest(_return, strSid, strUserID, strReqID, strReqUserID, strReqUserName);
    return;
  }

  void QueryAllOpenRequest(QueryAllOpenRequestRT& _return, const std::string& strSid, const std::string& strUserID, const QueryAllOpenRequestParam& qryparam) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->QueryAllOpenRequest(_return, strSid, strUserID, qryparam);
    }
    ifaces_[i]->QueryAllOpenRequest(_return, strSid, strUserID, qryparam);
    return;
  }

  void AddProduct(AddProductRT& _return, const std::string& strSid, const std::string& strUserID, const ProductInfo& pdt) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->AddProduct(_return, strSid, strUserID, pdt);
    }
    ifaces_[i]->AddProduct(_return, strSid, strUserID, pdt);
    return;
  }

  void RemoveProduct(ProductRTInfo& _return, const std::string& strSid, const std::string& strUserID, const std::string& strPdtID) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->RemoveProduct(_return, strSid, strUserID, strPdtID);
    }
    ifaces_[i]->RemoveProduct(_return, strSid, strUserID, strPdtID);
    return;
  }

  void ModifyProduct(ProductRTInfo& _return, const std::string& strSid, const std::string& strUserID, const std::string& strPdtID, const ProductInfo& pdt) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->ModifyProduct(_return, strSid, strUserID, strPdtID, pdt);
    }
    ifaces_[i]->ModifyProduct(_return, strSid, strUserID, strPdtID, pdt);
    return;
  }

  void QueryProduct(QueryProductRT& _return, const std::string& strSid, const std::string& strUserID, const std::string& strPdtID) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->QueryProduct(_return, strSid, strUserID, strPdtID);
    }
    ifaces_[i]->QueryProduct(_return, strSid, strUserID, strPdtID);
    return;
  }

  void QueryAllProduct(QueryAllProductRT& _return, const std::string& strSid, const std::string& strUserID) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->QueryAllProduct(_return, strSid, strUserID);
    }
    ifaces_[i]->QueryAllProduct(_return, strSid, strUserID);
    return;
  }

  void AddProductProperty(AddProductPropertyRT& _return, const std::string& strSid, const std::string& strUserID, const std::string& strPdtID, const ProductProperty& pdtppt) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->AddProductProperty(_return, strSid, strUserID, strPdtID, pdtppt);
    }
    ifaces_[i]->AddProductProperty(_return, strSid, strUserID, strPdtID, pdtppt);
    return;
  }

  void RemoveProductProperty(ProductRTInfo& _return, const std::string& strSid, const std::string& strUserID, const std::string& strPdtID, const std::string& strPdtpptID) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->RemoveProductProperty(_return, strSid, strUserID, strPdtID, strPdtpptID);
    }
    ifaces_[i]->RemoveProductProperty(_return, strSid, strUserID, strPdtID, strPdtpptID);
    return;
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class ProductServiceConcurrentClient : virtual public ProductServiceIf {
 public:
  ProductServiceConcurrentClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  ProductServiceConcurrentClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void AddProductType(AddProductTypeRT& _return, const std::string& strSid, const std::string& strUserID, const ProductType& pdttype);
  int32_t send_AddProductType(const std::string& strSid, const std::string& strUserID, const ProductType& pdttype);
  void recv_AddProductType(AddProductTypeRT& _return, const int32_t seqid);
  void RemoveProductType(ProductRTInfo& _return, const std::string& strSid, const std::string& strUserID, const std::string& strTypeID);
  int32_t send_RemoveProductType(const std::string& strSid, const std::string& strUserID, const std::string& strTypeID);
  void recv_RemoveProductType(ProductRTInfo& _return, const int32_t seqid);
  void ModifyProductType(ProductRTInfo& _return, const std::string& strSid, const std::string& strUserID, const ProductType& pdttype);
  int32_t send_ModifyProductType(const std::string& strSid, const std::string& strUserID, const ProductType& pdttype);
  void recv_ModifyProductType(ProductRTInfo& _return, const int32_t seqid);
  void QueryProductType(QueryProductTypeRT& _return, const std::string& strSid, const std::string& strUserID, const std::string& strTypeID);
  int32_t send_QueryProductType(const std::string& strSid, const std::string& strUserID, const std::string& strTypeID);
  void recv_QueryProductType(QueryProductTypeRT& _return, const int32_t seqid);
  void QueryAllProductType(QueryAllProductTypeRT& _return, const std::string& strSid, const std::string& strUserID);
  int32_t send_QueryAllProductType(const std::string& strSid, const std::string& strUserID);
  void recv_QueryAllProductType(QueryAllProductTypeRT& _return, const int32_t seqid);
  void AddOpenRequest(AddOpenRequestRT& _return, const std::string& strSid, const std::string& strUserID, const OpenRequest& opreq);
  int32_t send_AddOpenRequest(const std::string& strSid, const std::string& strUserID, const OpenRequest& opreq);
  void recv_AddOpenRequest(AddOpenRequestRT& _return, const int32_t seqid);
  void RemoveOpenRequest(ProductRTInfo& _return, const std::string& strSid, const std::string& strUserID, const std::string& strOpReqID);
  int32_t send_RemoveOpenRequest(const std::string& strSid, const std::string& strUserID, const std::string& strOpReqID);
  void recv_RemoveOpenRequest(ProductRTInfo& _return, const int32_t seqid);
  void ModifyOpenRequest(ProductRTInfo& _return, const std::string& strSid, const std::string& strUserID, const OpenRequest& opreq);
  int32_t send_ModifyOpenRequest(const std::string& strSid, const std::string& strUserID, const OpenRequest& opreq);
  void recv_ModifyOpenRequest(ProductRTInfo& _return, const int32_t seqid);
  void QueryOpenRequest(QueryOpenRequestRT& _return, const std::string& strSid, const std::string& strUserID, const std::string& strReqID, const std::string& strReqUserID, const std::string& strReqUserName);
  int32_t send_QueryOpenRequest(const std::string& strSid, const std::string& strUserID, const std::string& strReqID, const std::string& strReqUserID, const std::string& strReqUserName);
  void recv_QueryOpenRequest(QueryOpenRequestRT& _return, const int32_t seqid);
  void QueryAllOpenRequest(QueryAllOpenRequestRT& _return, const std::string& strSid, const std::string& strUserID, const QueryAllOpenRequestParam& qryparam);
  int32_t send_QueryAllOpenRequest(const std::string& strSid, const std::string& strUserID, const QueryAllOpenRequestParam& qryparam);
  void recv_QueryAllOpenRequest(QueryAllOpenRequestRT& _return, const int32_t seqid);
  void AddProduct(AddProductRT& _return, const std::string& strSid, const std::string& strUserID, const ProductInfo& pdt);
  int32_t send_AddProduct(const std::string& strSid, const std::string& strUserID, const ProductInfo& pdt);
  void recv_AddProduct(AddProductRT& _return, const int32_t seqid);
  void RemoveProduct(ProductRTInfo& _return, const std::string& strSid, const std::string& strUserID, const std::string& strPdtID);
  int32_t send_RemoveProduct(const std::string& strSid, const std::string& strUserID, const std::string& strPdtID);
  void recv_RemoveProduct(ProductRTInfo& _return, const int32_t seqid);
  void ModifyProduct(ProductRTInfo& _return, const std::string& strSid, const std::string& strUserID, const std::string& strPdtID, const ProductInfo& pdt);
  int32_t send_ModifyProduct(const std::string& strSid, const std::string& strUserID, const std::string& strPdtID, const ProductInfo& pdt);
  void recv_ModifyProduct(ProductRTInfo& _return, const int32_t seqid);
  void QueryProduct(QueryProductRT& _return, const std::string& strSid, const std::string& strUserID, const std::string& strPdtID);
  int32_t send_QueryProduct(const std::string& strSid, const std::string& strUserID, const std::string& strPdtID);
  void recv_QueryProduct(QueryProductRT& _return, const int32_t seqid);
  void QueryAllProduct(QueryAllProductRT& _return, const std::string& strSid, const std::string& strUserID);
  int32_t send_QueryAllProduct(const std::string& strSid, const std::string& strUserID);
  void recv_QueryAllProduct(QueryAllProductRT& _return, const int32_t seqid);
  void AddProductProperty(AddProductPropertyRT& _return, const std::string& strSid, const std::string& strUserID, const std::string& strPdtID, const ProductProperty& pdtppt);
  int32_t send_AddProductProperty(const std::string& strSid, const std::string& strUserID, const std::string& strPdtID, const ProductProperty& pdtppt);
  void recv_AddProductProperty(AddProductPropertyRT& _return, const int32_t seqid);
  void RemoveProductProperty(ProductRTInfo& _return, const std::string& strSid, const std::string& strUserID, const std::string& strPdtID, const std::string& strPdtpptID);
  int32_t send_RemoveProductProperty(const std::string& strSid, const std::string& strUserID, const std::string& strPdtID, const std::string& strPdtpptID);
  void recv_RemoveProductProperty(ProductRTInfo& _return, const int32_t seqid);
 protected:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  ::apache::thrift::async::TConcurrentClientSyncInfo sync_;
};

#ifdef _MSC_VER
  #pragma warning( pop )
#endif

}} // namespace

#endif
