/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "Product_constants.h"

namespace Product { namespace Service {

const ProductConstants g_Product_constants;

ProductConstants::ProductConstants() {
  PDT_SUCCESS_CODE = 0;

  PDT_FAILED_CODE = -1;

}

}} // namespace

