/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Trans_CONSTANTS_H
#define Trans_CONSTANTS_H

#include "Trans_types.h"

namespace Trans { namespace Service {

class TransConstants {
 public:
  TransConstants();

};

extern const TransConstants g_Trans_constants;

}} // namespace

#endif
